// Pre-populated recruiting targets — domain used for Logo.dev, ticker as logo fallback.
// Add entries here as members report gaps; no external lookup API required.
export const FIRMS = {
  'Goldman Sachs': { domain: 'goldmansachs.com', ticker: 'GS', aliases: ['gs'] },
  'Morgan Stanley': { domain: 'morganstanley.com', ticker: 'MS', aliases: ['ms'] },
  JPMorgan: { domain: 'jpmorgan.com', ticker: 'JPM', aliases: ['jpm', 'jp morgan'] },
  'Bank of America': { domain: 'bankofamerica.com', ticker: 'BAC', aliases: ['bofa', 'boa'] },
  Citigroup: { domain: 'citi.com', ticker: 'C', aliases: ['citi'] },
  'Wells Fargo': { domain: 'wellsfargo.com', ticker: 'WFC' },
  Barclays: { domain: 'barclays.com', ticker: 'BCS' },
  UBS: { domain: 'ubs.com', ticker: 'UBS' },
  'Credit Suisse': { domain: 'credit-suisse.com' },
  'Deutsche Bank': { domain: 'db.com', ticker: 'DB' },
  HSBC: { domain: 'hsbc.com', ticker: 'HSBC' },
  BNP: { domain: 'bnp.com', ticker: 'BNP' },
  'BNP Paribas': { domain: 'bnpparibas.com', ticker: 'BNP' },
  'RBC Capital Markets': { domain: 'rbccm.com', ticker: 'RY' },
  'TD Securities': { domain: 'tdsecurities.com', ticker: 'TD' },
  'BMO Capital Markets': { domain: 'bmo.com', ticker: 'BMO' },
  'Scotiabank': { domain: 'scotiabank.com', ticker: 'BNS' },
  Nomura: { domain: 'nomura.com', ticker: 'NMR' },
  Mizuho: { domain: 'mizuho.com', ticker: 'MFG' },
  'MUFG': { domain: 'mufg.jp', ticker: 'MUFG' },
  'Standard Chartered': { domain: 'sc.com', ticker: 'STAN' },
  'Jefferies': { domain: 'jefferies.com', ticker: 'JEF' },
  'Stifel': { domain: 'stifel.com', ticker: 'SF' },
  'Raymond James': { domain: 'raymondjames.com', ticker: 'RJF' },
  'William Blair': { domain: 'williamblair.com' },
  'Stephens Inc.': { domain: 'stephens.com' },
  'Piper Sandler': { domain: 'pipersandler.com', ticker: 'PIPR' },
  'Lincoln International': { domain: 'lincolninternational.com' },
  'Lazard': { domain: 'lazard.com', ticker: 'LAZ' },
  'Evercore': { domain: 'evercore.com', ticker: 'EVR' },
  'Centerview Partners': { domain: 'centerviewpartners.com' },
  'PJT Partners': { domain: 'pjtpartners.com', ticker: 'PJT' },
  'Moelis & Company': { domain: 'moelis.com', ticker: 'MC' },
  'Perella Weinberg': { domain: 'pwpartners.com', ticker: 'PWP' },
  'Perella Weinberg Partners': { domain: 'pwpartners.com', ticker: 'PWP' },
  'Guggenheim Partners': { domain: 'guggenheimpartners.com' },
  'Greenhill': { domain: 'greenhill.com' },
  'Houlihan Lokey': { domain: 'hl.com', ticker: 'HLI' },
  'Robert W. Baird': { domain: 'rwbaird.com' },
  'Allen & Company': { domain: 'allenandco.com' },
  'Qatalyst Partners': { domain: 'qatalyst.com' },
  'Raine Group': { domain: 'raine.com' },
  'LionTree': { domain: 'liontree.com' },
  'FT Partners': { domain: 'ftpartners.com' },
  'Solomon Partners': { domain: 'solomonpartners.com' },
  'Blackstone': { domain: 'blackstone.com', ticker: 'BX' },
  KKR: { domain: 'kkr.com', ticker: 'KKR' },
  Apollo: { domain: 'apollo.com', ticker: 'APO' },
  Carlyle: { domain: 'carlyle.com', ticker: 'CG' },
  'Warburg Pincus': { domain: 'warburgpincus.com' },
  'TPG': { domain: 'tpg.com' },
  'Bain Capital': { domain: 'baincapital.com' },
  'Silver Lake': { domain: 'silverlake.com' },
  'Vista Equity Partners': { domain: 'vistaequitypartners.com' },
  'General Atlantic': { domain: 'generalatlantic.com' },
  'Advent International': { domain: 'adventinternational.com' },
  'Thoma Bravo': { domain: 'thomabravo.com' },
  'Hellman & Friedman': { domain: 'hf.com' },
  'Providence Equity': { domain: 'provequity.com' },
  'Insight Partners': { domain: 'insightpartners.com' },
  'Francisco Partners': { domain: 'franciscopartners.com' },
  'GTCR': { domain: 'gtcr.com' },
  'Leonard Green': { domain: 'leonardgreen.com' },
  'Audax Group': { domain: 'audaxgroup.com' },
  'Golden Gate Capital': { domain: 'goldengatecap.com' },
  'Genstar Capital': { domain: 'gencap.com' },
  'Summit Partners': { domain: 'summitpartners.com' },
  'American Securities': { domain: 'american-securities.com' },
  'Clayton Dubilier & Rice': { domain: 'cdr-inc.com' },
  'Brookfield': { domain: 'brookfield.com', ticker: 'BN' },
  'BlackRock': { domain: 'blackrock.com', ticker: 'BLK' },
  Vanguard: { domain: 'vanguard.com' },
  Fidelity: { domain: 'fidelity.com' },
  'State Street': { domain: 'statestreet.com', ticker: 'STT' },
  'Northern Trust': { domain: 'northerntrust.com', ticker: 'NTRS' },
  Wellington: { domain: 'wellington.com' },
  'Capital Group': { domain: 'capitalgroup.com' },
  'T. Rowe Price': { domain: 'troweprice.com', ticker: 'TROW' },
  Invesco: { domain: 'invesco.com', ticker: 'IVZ' },
  'Franklin Templeton': { domain: 'franklintempleton.com', ticker: 'BEN' },
  'PIMCO': { domain: 'pimco.com' },
  'AllianceBernstein': { domain: 'alliancebernstein.com', ticker: 'AB' },
  'Man Group': { domain: 'man.com', ticker: 'EMG' },
  'Bridgewater Associates': { domain: 'bridgewater.com' },
  Citadel: { domain: 'citadel.com' },
  'Citadel Securities': { domain: 'citadelsecurities.com' },
  Point72: { domain: 'point72.com' },
  'Millennium Management': { domain: 'mlp.com' },
  'Two Sigma': { domain: 'twosigma.com' },
  'Jane Street': { domain: 'janestreet.com' },
  'D.E. Shaw': { domain: 'deshaw.com' },
  'HRT': { domain: 'hudsonrivertrading.com' },
  'Hudson River Trading': { domain: 'hudsonrivertrading.com' },
  'Jump Trading': { domain: 'jumptrading.com' },
  'Optiver': { domain: 'optiver.com' },
  'IMC Trading': { domain: 'imc.com' },
  'DRW': { domain: 'drw.com' },
  'Akuna Capital': { domain: 'akunacapital.com' },
  'Virtu Financial': { domain: 'virtu.com', ticker: 'VIRT' },
  'Susquehanna (SIG)': { domain: 'sig.com' },
  'Susquehanna International Group': { domain: 'sig.com' },
  'Balyasny Asset Management': { domain: 'bamfunds.com' },
  'Balyasny': { domain: 'bamfunds.com' },
  'ExodusPoint': { domain: 'exoduspoint.com' },
  'Schonfeld': { domain: 'schonfeld.com' },
  'Walleye Capital': { domain: 'walleyecapital.com' },
  'Squarepoint Capital': { domain: 'squarepoint-capital.com' },
  'WorldQuant': { domain: 'worldquant.com' },
  'AQR Capital Management': { domain: 'aqr.com' },
  'Elliott Management': { domain: 'elliottmgmt.com' },
  'Baupost Group': { domain: 'baupost.com' },
  'Third Point': { domain: 'thirdpoint.com' },
  'Pershing Square': { domain: 'pershingsquareholdings.com' },
  'Tiger Global': { domain: 'tigerglobal.com' },
  'Coatue Management': { domain: 'coatue.com' },
  'Lone Pine Capital': { domain: 'lonepinecapital.com' },
  'Viking Global': { domain: 'vikingglobal.com' },
  'DE Shaw': { domain: 'deshaw.com' },
  McKinsey: { domain: 'mckinsey.com' },
  'Boston Consulting Group': { domain: 'bcg.com', aliases: ['bcg'] },
  Bain: { domain: 'bain.com' },
  'Deloitte': { domain: 'deloitte.com' },
  'PwC': { domain: 'pwc.com' },
  'EY': { domain: 'ey.com' },
  'KPMG': { domain: 'kpmg.com' },
  'Accenture': { domain: 'accenture.com', ticker: 'ACN' },
  'Amazon': { domain: 'amazon.com', ticker: 'AMZN' },
  'Google': { domain: 'google.com', ticker: 'GOOGL' },
  'Microsoft': { domain: 'microsoft.com', ticker: 'MSFT' },
  'Meta': { domain: 'meta.com', ticker: 'META' },
  'Apple': { domain: 'apple.com', ticker: 'AAPL' },
  'Netflix': { domain: 'netflix.com', ticker: 'NFLX' },
  'Stripe': { domain: 'stripe.com' },
  'Palantir': { domain: 'palantir.com', ticker: 'PLTR' },
  'Databricks': { domain: 'databricks.com' },
  'Salesforce': { domain: 'salesforce.com', ticker: 'CRM' },
  'Oracle': { domain: 'oracle.com', ticker: 'ORCL' },
  'IBM': { domain: 'ibm.com', ticker: 'IBM' },
  'Intel': { domain: 'intel.com', ticker: 'INTC' },
  'NVIDIA': { domain: 'nvidia.com', ticker: 'NVDA' },
  'Tesla': { domain: 'tesla.com', ticker: 'TSLA' },
  'Ford': { domain: 'ford.com', ticker: 'F' },
  'General Motors': { domain: 'gm.com', ticker: 'GM' },
  'Procter & Gamble': { domain: 'pg.com', ticker: 'PG' },
  'Johnson & Johnson': { domain: 'jnj.com', ticker: 'JNJ' },
  'PepsiCo': { domain: 'pepsico.com', ticker: 'PEP' },
  'Coca-Cola': { domain: 'coca-colacompany.com', ticker: 'KO' },
  'Nike': { domain: 'nike.com', ticker: 'NKE' },
  'Target': { domain: 'target.com', ticker: 'TGT' },
  'Walmart': { domain: 'walmart.com', ticker: 'WMT' },
  'Costco': { domain: 'costco.com', ticker: 'COST' },
  'Home Depot': { domain: 'homedepot.com', ticker: 'HD' },
  'Lowe\'s': { domain: 'lowes.com', ticker: 'LOW' },
  'GE Aerospace': { domain: 'geaerospace.com', ticker: 'GE' },
  'Boeing': { domain: 'boeing.com', ticker: 'BA' },
  'Lockheed Martin': { domain: 'lockheedmartin.com', ticker: 'LMT' },
  'Northrop Grumman': { domain: 'northropgrumman.com', ticker: 'NOC' },
  'ExxonMobil': { domain: 'exxonmobil.com', ticker: 'XOM' },
  'Chevron': { domain: 'chevron.com', ticker: 'CVX' },
  'ConocoPhillips': { domain: 'conocophillips.com', ticker: 'COP' },
  'Marathon Petroleum': { domain: 'marathonpetroleum.com', ticker: 'MPC' },
  'KPMG Deal Advisory': { domain: 'kpmg.com' },
  'Deloitte Corporate Finance': { domain: 'deloitte.com' },
  'KeyBanc Capital Markets': { domain: 'key.com', ticker: 'KEY' },
  'Truist Securities': { domain: 'truist.com', ticker: 'TFC' },
  'Fifth Third Securities': { domain: '53.com', ticker: 'FITB' },
  'Huntington': { domain: 'huntington.com', ticker: 'HBAN' },
  'Regions Bank': { domain: 'regions.com', ticker: 'RF' },
  'PNC': { domain: 'pnc.com', ticker: 'PNC' },
  'M&T Bank': { domain: 'mtb.com', ticker: 'MTB' },
  'Comerica': { domain: 'comerica.com', ticker: 'CMA' },
  'Ohio National Financial Services': { domain: 'ohionational.com' },
  'Huntington Bank': { domain: 'huntington.com', ticker: 'HBAN' },
  'Nationwide': { domain: 'nationwide.com' },
  'Cardinal Health': { domain: 'cardinalhealth.com', ticker: 'CAH' },
  'Kroger': { domain: 'kroger.com', ticker: 'KR' },
  'Sherwin-Williams': { domain: 'sherwin-williams.com', ticker: 'SHW' },
  'Progressive': { domain: 'progressive.com', ticker: 'PGR' },
  'American Electric Power': { domain: 'aep.com', ticker: 'AEP' },
  'Danaher': { domain: 'danaher.com', ticker: 'DHR' },
  'Abbott': { domain: 'abbott.com', ticker: 'ABT' },
  'AbbVie': { domain: 'abbvie.com', ticker: 'ABBV' },
  'Medtronic': { domain: 'medtronic.com', ticker: 'MDT' },
  'Stryker': { domain: 'stryker.com', ticker: 'SYK' },
  'Boston Scientific': { domain: 'bostonscientific.com', ticker: 'BSX' },
  'S&P Global': { domain: 'spglobal.com', ticker: 'SPGI' },
  'Moody\'s': { domain: 'moodys.com', ticker: 'MCO' },
  'MSCI': { domain: 'msci.com', ticker: 'MSCI' },
  'FactSet': { domain: 'factset.com', ticker: 'FDS' },
  'Bloomberg': { domain: 'bloomberg.com' },
  'Refinitiv': { domain: 'refinitiv.com' },
  'Morningstar': { domain: 'morningstar.com', ticker: 'MORN' },
  'ICE': { domain: 'ice.com', ticker: 'ICE' },
  'CME Group': { domain: 'cmegroup.com', ticker: 'CME' },
  'Nasdaq': { domain: 'nasdaq.com', ticker: 'NDAQ' },
  'NYSE': { domain: 'nyse.com', ticker: 'ICE' },
  'Charles Schwab': { domain: 'schwab.com', ticker: 'SCHW' },
  'Robinhood': { domain: 'robinhood.com', ticker: 'HOOD' },
  'SoFi': { domain: 'sofi.com', ticker: 'SOFI' },
  Affirm: { domain: 'affirm.com', ticker: 'AFRM' },
};
